name = "ComplexPaths"
uuid = "a25e2219-d8cc-47b2-bc88-9b0dc7d4b2a3"
authors = ["ErrolSeders <errolbucy@gmail.com>"]
version = "0.1.0"

[deps]
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"

[compat]
Intervals = "1.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
